Repository geta-org/sex-adapt-mobile, pull requests merged in 2023-01, with the labels that each got.

#39 Feat/suggestion
  App.tsx
  src/@types/establishment.d.ts
  src/@types/navigation.d.ts
  src/@types/png.d.ts
  src/@types/styled.d.ts
  src/@types/svg.d.ts
  src/assets/index.ts
  src/components/BackButton/index.tsx
  src/components/BackButton/styles.ts
  src/components/Button/ButtonRound/index.tsx
  src/components/Button/ButtonRound/styles.ts
  src/components/Card/CardAccessibility/styles.ts
  src/components/Card/CardMotel/styles.ts
  src/components/Input/InputSearch/styles.ts
  src/components/Loading/styles.ts
  src/components/Map/CalloutView/index.tsx
  src/components/Map/CalloutView/styles.ts
  src/components/Map/MotelMarker/index.tsx
  src/components/Map/MotelMarker/styles.ts
  src/components/Map/UserMarker/index.tsx
  src/components/Map/UserMarker/styles.ts
  src/components/PriceRating/styles.ts
  src/contexts/useAuth.tsx
  src/routes/app.routes.tsx
  src/screens/App/Home/index.tsx
  src/screens/App/Home/styles.ts
  src/screens/App/Map/index.tsx
  src/screens/App/Map/styles.ts
  src/screens/App/MotelDetails/styles.ts
  src/screens/App/Suggestion/index.tsx
  src/screens/App/Suggestion/styles.ts
  src/screens/App/Support/index.tsx
  src/screens/App/Support/styles.ts
  src/screens/App/index.ts
  src/screens/Auth/Accessibility/index.tsx
  src/screens/Auth/Accessibility/styles.ts
  src/screens/Auth/RecoverPassword/index.tsx
  src/screens/Auth/RecoverPassword/styles.ts
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignIn/styles.ts
  src/screens/Auth/SignUp/index.tsx
  src/screens/Auth/SignUp/styles.ts
  src/screens/Auth/index.ts
  src/services/api.ts
  src/styles/theme.ts
Labels: enhancement

#43 Feature | Route Parameters
  src/@types/navigation.d.ts
  src/components/BackButton/styles.ts
  src/components/Card/CardMotel/index.tsx
  src/components/Modal/ModalConfirmation/styles.ts
  src/helpers/formattedText.ts
  src/screens/App/Home/styles.ts
  src/screens/App/MotelDetails/index.tsx
  src/screens/App/Support/styles.ts
  src/screens/Auth/Accessibility/styles.ts
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignIn/styles.ts
  src/screens/Auth/SignUp/index.tsx
Labels: enhancement

#48 Fix | Application does not open
  src/@types/navigation.d.ts
  src/components/BackButton/styles.ts
  src/components/Card/CardMotel/index.tsx
  src/components/Modal/ModalConfirmation/styles.ts
  src/helpers/formattedText.ts
  src/screens/App/Home/styles.ts
  src/screens/App/MotelDetails/index.tsx
  src/screens/App/Support/styles.ts
  src/screens/Auth/Accessibility/styles.ts
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignIn/styles.ts
  src/screens/Auth/SignUp/index.tsx
Labels: fix

#45 Refactor | Sign In
  package.json
  src/@types/navigation.d.ts
  src/components/BackButton/styles.ts
  src/components/Input/InputBase/index.tsx
  src/components/Input/InputBase/styles.ts
  src/components/Input/index.tsx
  src/components/Input/styles.ts
  src/screens/App/Home/styles.ts
  src/screens/App/Support/styles.ts
  src/screens/Auth/Accessibility/styles.ts
  src/screens/Auth/SignIn/index.tsx
  src/screens/Auth/SignIn/styles.ts
  yarn.lock
Labels: refactor

#46 Refactor | Recover Password
  src/components/BackButton/index.tsx
  src/components/Button/ButtonBack/index.tsx
  src/components/Button/ButtonBack/styles.ts
  src/components/ContinueButton/index.tsx
  src/components/ContinueButton/styles.ts
  src/screens/Auth/Accessibility/index.tsx
  src/screens/Auth/RecoverPassword/index.tsx
  src/screens/Auth/RecoverPassword/styles.ts
  src/screens/Auth/SignUp/index.tsx
Labels: refactor

#47 Refactor | Sign Up
  src/components/Input/InputForm/index.tsx
  src/screens/Auth/RecoverPassword/index.tsx
  src/screens/Auth/RecoverPassword/styles.ts
  src/screens/Auth/SignUp/index.tsx
  src/screens/Auth/SignUp/styles.ts
Labels: refactor

#44 Feature | User Preferences
  package.json
  src/@types/navigation.d.ts
  src/components/Button/ButtonBase/index.tsx
  src/components/Button/ButtonBase/styled.ts
  src/components/Filter/FilterSlider/index.tsx
  src/components/Filter/FilterSlider/styles.ts
  src/components/HeaderMotel/index.tsx
  src/components/Slider/index.tsx
  src/routes/app.routes.tsx
  src/screens/App/Filter/index.tsx
  src/screens/App/Filter/styles.ts
  src/screens/App/index.ts
  yarn.lock
Labels: enhancement
